### ISSUE TITLE
V10 foundry compatibility?

### ISSUE THREAD

**Issue by medeiros961030** [KayelGee/select-tool-everywhere#4]
Will you update your module to V10?

**Comment by KayelGee** [comment]
yes unless there's a technical limitation preventing me to update

**Comment by Gray-Geist** [comment]
Any update?

**Comment by KayelGee** [comment]
Moving multiple lights crashes foundry v10 and I still haven't figured out if there's a way for me to prevent that.

**Comment by KayelGee** [comment]
see #5 for the remaining issue that I don't know how to solve sorry
